import AppKit

final class SystemTextClipboardAdapter: ClipboardSourceAdapter {
    let id = "system.text"
    var displayName: String { L10n.tr("clipboard.source.system") }
    let capability = IntegrationCapabilityDeclaration(id: "clipboard.text", isOptional: false)

    private var items: [ClipboardItem] = []
    private var changeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    private var receive: ((ClipboardAdapterUpdate) -> Void)?

    private static let protectedTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword")
    ]
    private static let maximumTextBytes = 512 * 1_024

    func start(receive: @escaping (ClipboardAdapterUpdate) -> Void) {
        self.receive = receive
        // Do not ingest clipboard contents that existed before Hooky bar started.
        changeCount = NSPasteboard.general.changeCount
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.7, repeats: true) { [weak self] _ in
            self?.captureIfChanged()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        receive = nil
    }

    func copy(_ item: ClipboardItem) -> IntegrationResult {
        guard let text = item.text else { return .failed(.invalidConfiguration) }
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let copied = pasteboard.setString(text, forType: .string)
        changeCount = pasteboard.changeCount
        return copied ? .success : .failed(.commandRejected)
    }

    func remove(_ item: ClipboardItem) -> IntegrationResult {
        items.removeAll { $0.id == item.id }
        publish()
        return .success
    }

    static func shouldCapture(types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types else { return true }
        return protectedTypes.isDisjoint(with: types)
    }

    private func captureIfChanged() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount
        guard Self.shouldCapture(types: pasteboard.types),
              let text = pasteboard.string(forType: .string),
              text.utf8.count <= Self.maximumTextBytes,
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }

        items.removeAll { $0.text == text }
        let application = NSWorkspace.shared.frontmostApplication
        let item = ClipboardItem(
            id: "text:\(UUID().uuidString)",
            sourceID: id,
            sourceName: application?.localizedName ?? displayName,
            sourceBundleIdentifier: application?.bundleIdentifier,
            kind: .text,
            text: text,
            fileURL: nil,
            createdAt: Date()
        )
        items.insert(item, at: 0)
        items = Array(items.prefix(60))
        publish(inserted: item)
    }

    private func publish(inserted: ClipboardItem? = nil) {
        receive?(ClipboardAdapterUpdate(sourceID: id, items: items, insertedItem: inserted))
    }
}
